const express = require("express");
const getListingHandler = require("../controllers/api/getListingHandler");
const getAllListings = require("../controllers/api/getAllListing");
const updateViews = require("../controllers/api/updateViews");
const getPostComment = require("../controllers/api/getPostComments");
const router = express.Router();
router.get("/:start/:type/:offer/:furnished/:parking", getAllListings);
router.get("/:postId", getListingHandler);
router.get("/:postId/comment", getPostComment);
module.exports = router;
